### ISSUE TITLE
Updated Readme?

### ISSUE THREAD

**Issue by pauljones0** [lucalewin/sonar#1]
This project looks interesting.
I know nothing about Rust, but I have that same problem and I want to solve it. How can I help?

**Comment by lucalewin** [comment]
Thank you for your interest in this project.

- You could try to "measure" the latency with the help of [this video](https://www.youtube.com/watch?v=TjAa0wOe5k4) and then post the latency here.
- It could also be helpful if you could post the console log here.
- If you want you could add `debug!("samples: {}", samples.len());` into `src/server.rs` after  
```rust
// wait for samples from the audio capture thread
let samples = receiver.recv()?;
```  
in `send_audio_stream` and then post the sample size here (it should always be the same size).
